version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        OUTLOOK_USER: ${OUTLOOK_USER}
        OUTLOOK_PASS: ${OUTLOOK_PASS}
    environment:
      - NODE_ENV=development
      - OUTLOOK_USER=${OUTLOOK_USER}
      - OUTLOOK_PASS=${OUTLOOK_PASS}
    ports:
      - "8081:8081" 
      - "8080:8080" 
    volumes:
      - .:/app
    command: ["sh", "-c", "node server.js & npm start"]
