version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: chaofan-web:latest
    ports:
      - "8081:8081" 
      - "8080:8080" 
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
    command: ["sh", "-c", "node server.js & npm start"]
