name: Build and Deploy to ECR

on:
  push:
    branches:
      - main 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Docker Compose
      run: sudo apt-get update && sudo apt-get install docker-compose -y
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      with:
        mask-password: 'true'

    - name: Build, tag, and push docker image to Amazon ECR
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: my-ecr-repo
        IMAGE_TAG: ${{ github.sha }}
        OUTLOOK_USER: ${{ secrets.OUTLOOK_USER }}
        OUTLOOK_PASS: ${{ secrets.OUTLOOK_PASS }}
      run: |
        docker compose build --build-arg OUTLOOK_USER=$OUTLOOK_USER --build-arg OUTLOOK_PASS=$OUTLOOK_PASS
        docker tag my-ecr-repo:latest $REGISTRY/$REPOSITORY:$IMAGE_TAG
        docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
